export const GET_LIST_OF_THUMBNAILS_YEAR = "GET_LIST_OF_THUMBNAILS_YEAR";
export const GET_LIST_OF_THUMBNAILS_MONTHS = "GET_LIST_OF_THUMBNAILS_MONTHS";
export const GET_LIST_OF_THUMBNAILS_DAYS = "GET_LIST_OF_THUMBNAILS_DAYS";
export const GET_LIST_OF_THUMBNAILS_HOURS = "GET_LIST_OF_THUMBNAILS_HOURS";
export const GET_LIST_OF_THUMBNAILS_MINUTES = "GET_LIST_OF_THUMBNAILS_MINUTES";
export const GET_LIST_OF_THUMBNAILS_IMAGES = "GET_LIST_OF_THUMBNAILS_IMAGES";
