export const GET_LIST_OF_CAMERAS = "GET_LIST_OF_CAMERAS";
export const GET_CAMERA = "GET_CAMERA";
export const GET_REBROADCAST_PARAMS = "GET_REBROADCAST_PARAMS";
export const ADD_CAMERA = "ADD_CAMERA";
export const DELETE_CAMERA = "DELETE_CAMERA";
export const UPDATE_CAMERA = "UPDATE_CAMERA";
